import { ArrowRight, Check, FolderKanban, Globe2, LayoutDashboard, ShieldCheck, Users } from "lucide-react";
import { Link } from "react-router-dom";
import { useI18n } from "../lib/i18n";

export default function Landing() {
  const { locale, setLocale, t } = useI18n();
  const features = [{ Icon: LayoutDashboard, title: t.feature1, body: t.feature1Body }, { Icon: Users, title: t.feature2, body: t.feature2Body }, { Icon: ShieldCheck, title: t.feature3, body: t.feature3Body }];
  return <main className="landing min-h-screen overflow-hidden bg-[#f7f8f2] text-[#15231d]">
    <nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8"><Link to="/" className="flex items-center gap-3 text-lg font-bold"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#163c2d] text-white"><FolderKanban size={20}/></span>ProjectPulse</Link><div className="flex items-center gap-2 sm:gap-3"><label className="relative hidden items-center sm:flex"><Globe2 className="pointer-events-none absolute left-3" size={15}/><select aria-label={t.language} value={locale} onChange={e=>setLocale(e.target.value as "pt-BR"|"en")} className="rounded-full border border-[#d9ddd3] bg-white py-2 pl-9 pr-4 text-sm font-medium"><option value="pt-BR">PT-BR</option><option value="en">EN</option></select></label><Link to="/login" className="rounded-full px-4 py-2 text-sm font-semibold hover:bg-white">{t.login}</Link><Link to="/register" className="rounded-full bg-[#163c2d] px-4 py-2 text-sm font-semibold text-white shadow-sm hover:bg-[#24533f]">{t.signup}</Link></div></nav>
    <section className="mx-auto grid max-w-7xl gap-14 px-5 pb-20 pt-14 lg:grid-cols-[1.02fr_.98fr] lg:px-8 lg:pb-28 lg:pt-20"><div className="flex flex-col justify-center"><div className="mb-6 flex w-fit items-center gap-2 rounded-full border border-[#cbd7cc] bg-white/70 px-3 py-1.5 text-xs font-bold uppercase tracking-[.16em] text-[#35614e]"><span className="h-2 w-2 rounded-full bg-[#e49b51]"/>{t.heroEyebrow}</div><h1 className="max-w-2xl text-5xl font-semibold leading-[1.02] tracking-[-.045em] sm:text-6xl lg:text-7xl">{t.heroTitle}</h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#5b6962]">{t.heroBody}</p><div className="mt-9 flex flex-wrap gap-3"><Link to="/register" className="flex items-center gap-2 rounded-full bg-[#e6803f] px-6 py-3.5 font-bold text-white shadow-[0_10px_30px_rgba(230,128,63,.25)] hover:bg-[#d86f31]">{t.start}<ArrowRight size={18}/></Link><a href="#recursos" className="rounded-full border border-[#d2d8cf] bg-white px-6 py-3.5 font-bold hover:border-[#9eaaa1]">{t.demo}</a></div><p className="mt-6 flex items-center gap-2 text-sm text-[#68766f]"><ShieldCheck size={17} className="text-[#37785a]"/>{t.trusted}</p></div>
    <div className="relative"><div className="absolute -inset-10 rounded-full bg-[#dfe9d7] blur-3xl"/><div className="relative overflow-hidden rounded-[2rem] border border-white/80 bg-white p-3 shadow-[0_35px_90px_rgba(42,66,53,.16)]"><div className="rounded-[1.35rem] bg-[#f4f6f0] p-4 sm:p-6"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-[#7b8881]">{t.dashboard}</p><h2 className="mt-1 text-xl font-bold">Studio Norte</h2></div><div className="flex -space-x-2">{["AM","DS","JP"].map((x,i)=><span key={x} className={`grid h-9 w-9 place-items-center rounded-full border-2 border-white text-[10px] font-bold ${["bg-[#f1b37b]","bg-[#9ec7b1]","bg-[#9db1d3]"][i]}`}>{x}</span>)}</div></div><div className="grid gap-3 sm:grid-cols-3"><Metric label={t.activeProjects} value="12"/><Metric label={t.progress} value="74%"/><Metric label={t.thisWeek} value="18"/></div><div className="mt-4 rounded-2xl bg-white p-5"><div className="mb-5 flex items-center justify-between"><b>{t.projects}</b><span className="rounded-full bg-[#e9f3eb] px-3 py-1 text-xs font-bold text-[#31704f]">{t.onTrack}</span></div>{[["Website Aurora",86,"#e6803f"],["Expansão Sul",62,"#3f795f"],["Mobile 2.0",43,"#6f82a8"]].map(([name,n,color])=><div key={name as string} className="mb-5 last:mb-0"><div className="mb-2 flex justify-between text-sm"><span className="font-semibold">{name}</span><span>{n}%</span></div><div className="h-2 rounded-full bg-[#edf0ea]"><div className="h-2 rounded-full" style={{width:`${n}%`,background:color as string}}/></div></div>)}</div></div></div></div></section>
    <section id="recursos" className="bg-[#163c2d] px-5 py-20 text-white"><div className="mx-auto grid max-w-7xl gap-5 md:grid-cols-3">{features.map(({Icon,title,body})=><article key={title} className="rounded-3xl border border-white/10 bg-white/[.06] p-7"><Icon size={25} className="text-[#f0a366]"/><h3 className="mt-7 text-xl font-bold">{title}</h3><p className="mt-3 leading-7 text-white/65">{body}</p><Check className="mt-6 text-[#86bda0]" size={18}/></article>)}</div></section>
  </main>;
}
function Metric({label,value}:{label:string;value:string}) { return <div className="rounded-2xl bg-white p-4"><p className="text-xs text-[#78847e]">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></div> }
