apiVersion: v1
kind: Service
metadata:
  name: tabor-flow-api
  namespace: tabor-flow
spec:
  type: ClusterIP
  selector:
    app: tabor-flow-api
  ports:
    - name: http
      port: 4000
      targetPort: http
